#!/bin/sh

# This script detects and compiles to pdf the changes in the /typst directory

# To set this directory as your git hooks directory, run:
#   git config core.hooksPath "hooks"

remote=origin/main
typst_dir="notes/typst"
out_dir="notes/"
edited_typst_files="$(git diff --name-only --staged $remote -- $typst_dir)"

# if no files have changed
if [ -z "$edited_typst_files" ]; then
    echo "No pdfs were compiled"
    exit 0
fi

echo "Compiling latest changes to pdfs..."

# start compiling to pdfs
for file in $(ls "$typst_dir"); do
    # skip non .typ files
    if [ ! "${file##*.}" = "typ" ]; then continue; fi
    # skip .mod.typ files for compilation
    if [ "${file#*.}" = "mod.typ" ]; then continue; fi

    # replace .mod.typ to .typ and prepend the out_dir
    out_file="$(basename "papers/${file%%.*}").pdf"
    typst compile "$typst_dir/$file" "$out_dir/$out_file"
    echo " compiled $out_file"
done

git add "$out_dir"
